"""golden.h for the two-stage export: one centre's int8 trunk inputs and outputs,
and one block's raw features with its expected projections, from golden.json.

    python -m train.golden2 export/twostage1
"""

import argparse
import json
from pathlib import Path


def arr(name, ctype, vals, per=16, fmt="{}"):
    rows = [", ".join(fmt.format(v) for v in vals[i:i + per]) for i in range(0, len(vals), per)]
    return f"static const {ctype} {name}[{len(vals)}] = {{\n  " + ",\n  ".join(rows) + "\n};\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("export", type=Path)
    a = ap.parse_args()
    g = json.loads((a.export / "golden" / "golden.json").read_text())
    m = json.loads((a.export / "model_meta.json").read_text())
    c = g["check_centre"]
    n = c + 2  # the block whose arrival produces centre c
    x28 = g["fe"][n] + g["mel_flux16"][n]
    heads = m["stage_b"]["outputs"]
    out = [
        "/* Generated by train/golden2.py from golden.json; see specs/two-stage-spec.md. */",
        "#pragma once", "#include <stdint.h>", "",
        f"#define GOLDEN2_SHA_A \"{m['stage_a']['sha256']}\"",
        f"#define GOLDEN2_SHA_B \"{m['stage_b']['sha256']}\"",
        f"#define GOLDEN2_CENTRE {c}   /* block index from boot of golden/pcm_s16le_48k.raw */",
        f"#define GOLDEN2_BLOCK {n}    /* the newest block when centre GOLDEN2_CENTRE is produced */", "",
        "/* step 1-5 at block GOLDEN2_BLOCK: 28 raw features, the feedback value, both projections */",
        arr("golden2_x28", "float", x28, 7, "{:.6f}f"),
        f"static const float golden2_fb = {g['fb3'][n]:.6f}f;\n",
        arr("golden2_proj_a", "float", g["proj_a"][n], 6, "{:.5f}f"),
        arr("golden2_proj_b", "float", g["proj_b"][n], 6, "{:.5f}f"),
        "/* steps 3 and 6 at centre GOLDEN2_CENTRE: full int8 trunk inputs (+-1 LSB) and raw outputs */",
        arr("golden2_a_input", "int8_t", g["a_input_int8"]),
        f"static const int8_t golden2_a_beat = {g['a_output_int8']['beat'][0]};\n",
        arr("golden2_b_input", "int8_t", g["b_input_int8"]),
    ]
    for h in m["stage_b"]["outputs"]:
        v = g["b_output_int8"][h]
        out.append(arr(f"golden2_b_{h}", "int8_t", v) if len(v) > 1 else
                   f"static const int8_t golden2_b_{h} = {v[0]};  /* {heads[h]['tensor']} */\n")
    (a.export / "golden" / "golden.h").write_text("\n".join(out))
    print("wrote", a.export / "golden" / "golden.h")


if __name__ == "__main__":
    main()
